### ISSUE TITLE
No directive found with exportAs 'ngxTouchKeyboard'

### ISSUE THREAD

**Issue by guirms** [mohsen77sk/angular-touch-keyboard#14]
I'm trying to use this really great lib in my Angular 16 application, but even if I follow the read.me instructions, I can't create the <input>
This is my app.module:
```
import { NgxTouchKeyboardModule }  from 'ngx-touch-keyboard';
...
@NgModule({
    declarations: [...],
    providers: [...],
    bootstrap: [AppComponent],
    imports: [..., NgxTouchKeyboardModule]
})
```
This is my html code:
`<input type="text" ngxTouchKeyboard #touchKeyboard="ngxTouchKeyboard" (focus)="touchKeyboard.openPanel()"/>`

And this the error that I receive: **No directive found with exportAs 'ngxTouchKeyboard'**
Image:
![image](https://github.com/mohsen77sk/angular-touch-keyboard/assets/85650237/c603805b-d0bb-4a16-b6bc-e4e95df0036f)

**Comment by mohsen77sk** [comment]
Hi @guirms 
I'd like to thank you for your attention.

Please import `"NgxTouchKeyboardModule"` to Module of declaration `"ProductionTimesDialogComponent"`.

**Comment by guirms** [comment]
Thanks @mohsen77sk, this works! I was using a standalone component, so all I need to do was import this module properly at my component class
