### ISSUE TITLE
In nxBootstrap and Materials modals/dialogs

### ISSUE THREAD

**Issue by Dpellowski** [mohsen77sk/angular-touch-keyboard#3]
In these two components they keyboard gets overshadowed and doesn't attach itselfs to the inputs inside the modals/dialogs.

**Comment by mohsen77sk** [comment]
Hi @Dpellowski,

I'd like to thank you for your attention.
The demo now includes a material dialog that you can review. Please, if it has any issues, let me know.

If you provide me with a sample in nxBootstrap modals, I will be able to identify your issue.
