### ISSUE TITLE
Angular 14.1.0

### ISSUE THREAD

**Issue by e404r** [mohsen77sk/angular-touch-keyboard#6]
Angular 14.1.0  Neither version works

**Comment by mohsen77sk** [comment]
Hi @e404r

I'd like to thank you for your attention.
Please use version 2.2.0 for angular 14.

Demo for version 2.2.0 on angular 14 :
https://stackblitz.com/edit/angular-touch-keyboard-demo

**Comment by e404r** [comment]
npm ERR!   @angular/common@"^14.1.0" from the root project
npm ERR!   peer @angular/common@">=14.0.0" from ngx-touch-keyboard@2.2.0
npm ERR!   node_modules/ngx-touch-keyboard
npm ERR!     ngx-touch-keyboard@"2.2.0" from the root project
npm ERR!

**Comment by e404r** [comment]
npm ERR!   @angular/common@"^14.1.0" from the root project
npm ERR!   peer @angular/common@">=14.0.0" from ngx-touch-keyboard@2.2.0
npm ERR!   node_modules/ngx-touch-keyboard
npm ERR!     ngx-touch-keyboard@"2.2.0" from the root project
npm ERR!

**Comment by mohsen77sk** [comment]
Did you install @angular/cdk ?

**Comment by e404r** [comment]
> Did you install @angular/cdk ?

Yes 🫡 But nope
